### ISSUE TITLE
[Feature Request] restful api like Yake

### ISSUE THREAD

**Issue by ghost** [LIAAD/kep#1]
Hi guys,

Hope you are all well !

We used Yake for a project with its flask api and it was flawless. 
Thanks again for sharing this amazing tech. :-)

Now for Kep, we would like to test it also on a dataset and we have the following questions:
- Is it possible to publish a Dockerfile with flask server for kep ?
- Is it somehow too complicated or is it already on your roadmap ?

Thanks in advance for insights and inputs on that topic.

Cheers,
X

**Comment by rncampos** [comment]
Hi. Thanks for your comment. We are glad that you use YAKE!. 
As for your request it is not on the roadmap. But you already have KEP as a dockerfile to play wit [https://hub.docker.com/r/liaad/kep].

Best

**Comment by ghost** [comment]
Hi @rncampos ,

Hope you are all well !

I created a new dockerfile with a rest api that you can preview at https://github.com/x0rzkov/kep/tree/dockerize

Are you interested by a PR ?

Cheers,
X

**Comment by arianpasquali** [comment]
Yes! Sure!
We are checking the PR.

@rncampos   let me know what you think too.

best regards
Arian Pasquali

**Comment by ghost** [comment]
@rncampos let me know if you are interested, I just set the YAKE extractor, shall I add all the others ?

**Comment by rncampos** [comment]
> 
> 
> @rncampos let me know if you are interested, I just set the YAKE extractor, shall I add all the others ?

**Comment by rncampos** [comment]
> 
> 
> @rncampos let me know if you are interested, I just set the YAKE extractor, shall I add all the others ?

@x0rzkov can you send me an email to ricardo.campos@ipt.pt ?
